# Generated by Django 6.1.1 on 2026-10-05 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
